services:
    mqtt:
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        volumes:
            - './mosquitto-data:/mosquitto'
        ports:
            - '1883:1883'
            - '9001:9001'
        command: 'mosquitto -c /mosquitto-no-auth.conf'

    zigbee2mqtt:
        container_name: zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt
        volumes:
            - ./zigbee2mqtt-data:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8080:8080
        environment:
            - TZ=Europe/Berlin
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0


    telegraf:
        image: telegraf:1.18-alpine
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        depends_on:
            - influxdb
        links:
            - influxdb
        ports:
            - '8125:8125'

    influxdb:
        image: influxdb:1.8-alpine
        env_file: configuration.env
        ports:
        - '8086:8086'
        volumes:
        - ./influxdb_data:/var/lib/influxdb

    grafana:
        image: grafana/grafana:8.0.2
        depends_on:
        - influxdb
        env_file: configuration.env
        links:
        - influxdb
        ports:
        - '3000:3000'
        volumes:
        - ./grafane/data:/var/lib/grafana
        - ./grafana/provisioning/:/etc/grafana/provisioning/
        - ./grafana/dashboards/:/var/lib/grafana/dashboards/


    # mongo:
    #     image: mongodb/mongodb-community-server:6.0.15-ubi9
    #     container_name: mongo
    #     restart: unless-stopped
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - $PWD/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    #         - $PWD/mongo/data:/data/db
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=admin
    #         - MONGO_INITDB_ROOT_PASSWORD=public
    #         - MONGO_INITDB_DATABASE=iot_data

