services:
    mqtt:
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        volumes:
            - './mosquitto-data:/mosquitto'
        ports:
            - '1883:1883'
            - '9001:9001'
        command: 'mosquitto -c /mosquitto-no-auth.conf'

    zigbee2mqtt:
        container_name: zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt
        volumes:
            - ./zigbee2mqtt-data:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8080:8080
        environment:
            - TZ=Europe/Berlin
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0


    telegraf:
        image: telegraf:1.30-alpine
        restart: unless-stopped
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        depends_on:
            - influxdb
            - mqtt
        links:
            - influxdb
        ports:
            - '8125:8125'

    influxdb:
        image: influxdb:2.7-alpine
        restart: unless-stopped
        env_file: configuration.env
        ports:
        - '8086:8086'
        volumes:
          - ./influxdb_data:/var/lib/influxdb:z
        user: "1000:1000"

    grafana:
        image: grafana/grafana:11.2.3
        restart: unless-stopped
        depends_on:
        - influxdb
        env_file: configuration.env
        links:
        - influxdb
        ports:
        - '3000:3000'
