services:
    mqtt:
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        volumes:
            - './mosquitto-data:/mosquitto'
        ports:
            - '1883:1883'
            - '9001:9001'
        command: 'mosquitto -c /mosquitto-no-auth.conf'

    zigbee2mqtt:
        container_name: zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt
        volumes:
            - ./zigbee2mqtt-data:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8080:8080
        environment:
            - TZ=Europe/Berlin
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0


    emqx:
        image: emqx:5.8.1
        container_name: emqx
        healthcheck:
            test: ["CMD", "emqx", "ping"]
            interval: 10s
            timeout: 10s
            retries: 12
        volumes:
            - $PWD/emqx:/opt/emqx/data/configs
        ports:
            - 1883:1883
            - 18083:18083

    mongo:
        image: mongo:4.4.6
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - $PWD/mongo/init.js:/docker-entrypoint-initdb.d/init.js
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=public
            - MONGO_INITDB_DATABASE=iot_data

